# Data Handling & Visualization 1 — Tabular data, Excel, and CSV

**Digital Foundation for Chemical Engineers**  \n
Duration: 60 minutes

## Today’s goal
Recognise tidy process data, understand the roles of Excel and CSV files, and start working with tables in Python. We will use the `pandas` library, a widely used tool for tabular data.

## 1. Why data management matters (10 min)

A plant may record thousands of sensor values, laboratory results, and batch records. Useful analysis depends on data being understandable and traceable.

### A tidy-table habit
- One **row** = one observation (for example, one hourly reading).
- One **column** = one variable (for example, temperature in °C).
- One **cell** = one value.
- Give columns meaningful names including units: `flow_m3_h`, not `Flow1`.

Excel is convenient for manual inspection; **CSV** is a plain-text table format that moves easily between Excel, Python, and reporting tools.

## 2. DataFrames: tables in Python (12 min)

A pandas **DataFrame** is like a spreadsheet table in Python. It has named columns and numbered rows. Run this cell; the first execution may take a moment while the library loads.

If `pandas` is unavailable in a new Codespace, run `pip install pandas` in the terminal, then restart the kernel.

In [ ]:
#pip install pandas

2506.37s - pydevd: Sending message related to process being replaced timed-out after 5 seconds

Requirement already satisfied: pandas in /usr/local/python/3.14.2/lib/python3.14/site-packages (3.0.6)
Requirement already satisfied: numpy>=2.3.3 in /usr/local/python/3.14.2/lib/python3.14/site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [46]:
import pandas as pd

process_data = pd.DataFrame({
    'sr_no': ['1', '2', '3', '4', '5'],
    'hour': [8, 9, 10, 11, 12],
    'temperature_c': [72.1, 73.5, 75.2, 74.8, 76.0],
    'pressure_bar': [4.8, 4.9, 5.1, 5.0, 5.2],
    'flow_m3_h': [12.0, 12.3, 11.9, 12.1, 12.4]
})
process_data

  sr_no  hour  temperature_c  pressure_bar  flow_m3_h
0     1     8           72.1           4.8       12.0
1     2     9           73.5           4.9       12.3
2     3    10           75.2           5.1       11.9
3     4    11           74.8           5.0       12.1
4     5    12           76.0           5.2       12.4

**Run and modify (4 min):** Change a temperature value, rerun the cell, and observe the changed table. Add a `ph` column with five values.

**Challenge:** Create a second DataFrame for three batches with columns `batch_id`, `mass_kg`, and `yield_percent`.

In [26]:

import pandas as pd
process_data = pd.DataFrame({
    
    'sr_no': ['1', '2', '3', '4', '5'],
    'NAMES': [ 'ARYAN', 'PARTH', 'MANAV' , 'VAIBHAV', 'UJJU'],
    'hour': [8, 9, 10, 11, 12],
    'temperature_c': [72.1, 73.5, 75.2, 74.8, 76.0],
    'pressure_bar': [4.8, 4.9, 5.1, 5.0, 5.2],
    'flow_m3_h': [12.0, 12.3, 11.9, 12.1, 12.4],
    'pH': [7.1, 7.2, 7.3, 7.4, 7.5]
})
process_data

  sr_no    NAMES  hour  temperature_c  pressure_bar  flow_m3_h   pH
0     1    ARYAN     8           72.1           4.8       12.0  7.1
1     2    PARTH     9           73.5           4.9       12.3  7.2
2     3    MANAV    10           75.2           5.1       11.9  7.3
3     4  VAIBHAV    11           74.8           5.0       12.1  7.4
4     5     UJJU    12           76.0           5.2       12.4  7.5

## 3. Inspect before analysing (15 min)

Never jump directly to a conclusion from a new file. First inspect its size, column names, data types, and a few rows. `head()` gives the first rows; `info()` describes columns; `describe()` gives numerical summaries.

In [27]:
print('Shape (rows, columns):', process_data.shape)
print('\nColumn names:', list(process_data.columns))
display(process_data.head())
process_data.info()
display(process_data.describe())

Shape (rows, columns): (5, 7)

Column names: ['sr_no', 'NAMES', 'hour', 'temperature_c', 'pressure_bar', 'flow_m3_h', 'pH']

  sr_no    NAMES  hour  temperature_c  pressure_bar  flow_m3_h   pH
0     1    ARYAN     8           72.1           4.8       12.0  7.1
1     2    PARTH     9           73.5           4.9       12.3  7.2
2     3    MANAV    10           75.2           5.1       11.9  7.3
3     4  VAIBHAV    11           74.8           5.0       12.1  7.4
4     5     UJJU    12           76.0           5.2       12.4  7.5

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   sr_no          5 non-null      str
 1   NAMES          5 non-null      str
 2   hour           5 non-null      int64
 3   temperature_c  5 non-null      float64
 4   pressure_bar   5 non-null      float64
 5   flow_m3_h      5 non-null      float64
 6   pH             5 non-null      float64
dtypes: float64(4), int64(1), str(2)
memory usage: 412.0 bytes

            hour  temperature_c  pressure_bar  flow_m3_h        pH
count   5.000000       5.000000      5.000000   5.000000  5.000000
mean   10.000000      74.320000      5.000000  12.140000  7.300000
std     1.581139       1.535252      0.158114   0.207364  0.158114
min     8.000000      72.100000      4.800000  11.900000  7.100000
25%     9.000000      73.500000      4.900000  12.000000  7.200000
50%    10.000000      74.800000      5.000000  12.100000  7.300000
75%    11.000000      75.200000      5.100000  12.300000  7.400000
max    12.000000      76.000000      5.200000  12.400000  7.500000

**Try it (5 min):** Answer from the output: How many readings are present? Which column has the highest average? Are all columns numerical?

**Challenge:** Use `process_data['temperature_c'].mean()` to calculate the mean directly, then format it to two decimals.

In [28]:
print(f"{process_data['temperature_c'].mean():.2f}")

74.32

## 4. Excel and CSV: practical workflow (10 min)

A recommended workflow for this course:

1. Collect or export a controlled data table from a spreadsheet/system.
2. Save a working copy as **CSV UTF-8** with a clear file name and units in headers.
3. Import to Python, inspect it, clean it, then create repeatable outputs.
4. Keep the raw source unchanged; save cleaned data separately.

Avoid merged cells, decorative title rows, and mixed units in a single numeric column: they make reliable analysis harder.

## Pair task: design a data table (10 min)

You are recording hourly data from a heat exchanger. Propose five column names for time, inlet/outlet temperatures, flow, and a status note. Include units in appropriate names.

Then add a `delta_t_c` column below.

**Challenge:** Explain why storing `72 °C` as text is less useful than storing `72` in `temperature_c`.

In [33]:
process_data = pd.DataFrame({
    
    'TIME_hour': [8, 9, 10, 11, 12],
    'inlet_temperature_c': [72.1, 73.5, 75.2, 74.8, 76.0],
    'outlet_temperature_c': [68.5, 69.2, 70.1, 69.8, 70.5],
    'flow_m3_h': [12.0, 12.3, 11.9, 12.1, 12.4],
    'status': ['normal', 'precaution', 'hazardous', 'normal', 'danger']
})

process_data['delta_t_c'] = process_data['inlet_temperature_c'] - process_data['outlet_temperature_c']
process_data
print('Shape (rows, columns):', process_data.shape)
print('\nColumn names:', list(process_data.columns))
display(process_data.head())
process_data.info()
display(process_data.describe())

Shape (rows, columns): (5, 6)

Column names: ['TIME_hour', 'inlet_temperature_c', 'outlet_temperature_c', 'flow_m3_h', 'status', 'delta_t_c']

,TIME_hour,inlet_temperature_c,outlet_temperature_c,flow_m3_h,status,delta_t_c
0,8,72.1,68.5,12.0,normal,3.6
1,9,73.5,69.2,12.3,precaution,4.3
2,10,75.2,70.1,11.9,hazardous,5.1
3,11,74.8,69.8,12.1,normal,5.0
4,12,76.0,70.5,12.4,danger,5.5

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   TIME_hour             5 non-null      int64
 1   inlet_temperature_c   5 non-null      float64
 2   outlet_temperature_c  5 non-null      float64
 3   flow_m3_h             5 non-null      float64
 4   status                5 non-null      str
 5   delta_t_c             5 non-null      float64
dtypes: float64(4), int64(1), str(1)
memory usage: 372.0 bytes

,TIME_hour,inlet_temperature_c,outlet_temperature_c,flow_m3_h,delta_t_c
count,5.000000,5.000000,5.000000,5.000000,5.000000
mean,10.000000,74.320000,69.620000,12.140000,4.700000
std,1.581139,1.535252,0.785493,0.207364,0.751665
min,8.000000,72.100000,68.500000,11.900000,3.600000
25%,9.000000,73.500000,69.200000,12.000000,4.300000
50%,10.000000,74.800000,69.800000,12.100000,5.000000
75%,11.000000,75.200000,70.100000,12.300000,5.100000
max,12.000000,76.000000,70.500000,12.400000,5.500000

## Exit check

You can distinguish Excel from CSV, explain tidy rows and columns, construct a DataFrame, and inspect a new table before trusting it. Next hour: import and export real CSV files.